puppetlabs/cisco_ios

.sync.yml
Gemfile

This is necessary for cloning to work in our travis.org since this repo has been made public. It does not support ssh cloning.

(maint) - Update Clone from ssh to https 

---

lib/puppet/provider/network_dns/command.yaml
lib/puppet/provider/network_dns/ios.rb
spec/acceptance/network_dns_spec.rb
spec/unit/puppet/provider/network_dns/test_data.yaml

This commit fixes a couple of issues with network_dns
First is the change in CLI from `domain-name` / `domain-list` to `domain name` / `domain list`
Starting in IOS 12.2 the commands were moved to the later format.
Although systems still support setting via the old style, and even report in it - it is no longer preferred.
Addtionally most systems now report the value in new style.
This commit takes that into account by reading either format, and only setting in the new one.
The second is the handling of name-server's specified on a single line.
At some point IOS moved from multiple single value entries to a single multi-value entry
```
ip name-server 1.1.1.1
ip name-server 1.0.0.1
ip name-server 192.168.198.1
ip name-server 192.168.198.1 1.1.1.1 1.0.0.1
```
This commit takes those values …

(FM-7029) Fixup network_dns

---

README.md
examples/ios_config.pp
lib/puppet/provider/ios_config/ios.rb
lib/puppet/type/ios_config.rb
spec/acceptance/ios_config_spec.rb

This PR adds two major sets of functionality
The first is idempotency when being run from a master.  We use the canonicalize feature of RSAPI to execute idempotent_regex when set to determine if resource is already in desired state.
The second is regex options via idempotent_regex_options.  This allows users to specify regex options such as ignorecase and multiline.
```Puppet
ios_config { 'vty100':
command          => "
line vty 100
login local
transport input telnet ssh",
idempotent_regex => "line VTY 100\n login local\n transport input telnet ssh\n",
idempotent_regex_options => ['ignorecase'],
}
ios_config { 'vty200':
command          => "
line vty 200
login local
transport input telnet ssh",
idempotent_regex => "line VTY 200\n login local\n transport input telnet ssh\n", …
```

(FM-6990) ios_config idempotent via master and regex options

---

metadata.json
spec/spec_helper_acceptance.rb

Now that netdev_stdlib 0.14.0 has been released on the forge, update to use released version

(FM-7025) Move to netdev_stdlib 0.14.0

---

lib/puppet/util/network_device/cisco_ios/device.rb

This commit adds matching of `[OK]` in addition to bytes copied.

(maint) expand running_config_save regex

---

lib/puppet/provider/banner/command.yaml
spec/unit/puppet/provider/banner/test_data.yaml

We were using a # as the control char for setting banners - this conflices with the prompt
My bad.

(FM-7067) fix banner set regex

---

README.md

Normalize references to HOCON and YAML.
Correct related documentation.
Cleanup markdown formatting.

(FM-7069) hocon vs yaml

---

spec/acceptance/ntp_server_spec.rb

The 'future' build of PE device when outputting to yaml uses symbols for ensure fields. This allows yaml load to read symbols

(maint) NTP Server acceptance test - allow symbol on yaml load

---

lib/puppet/util/network_device/cisco_ios/device.rb

This prevents any previous config eg. Banner changes from
being picked up as the current prompt.

(FM-7067) Send a newline on Config T mode to clear prompt

---

lib/puppet/util/network_device/cisco_ios/command.yaml
lib/puppet/util/network_device/cisco_ios/device.rb

This commit adds the ability use custom enable password prompts as well as handles authentication and authorization errors for commands
Users are able to specify custom prompts when using RADIUS.  This was causing issues with the module timing out.  I went with a more elegant regex that either looks an empty line (which is actually the input portion of the password prompt, or the end of the CLI prompt - which means we either threw an error, or enabled w/out asking for a password.
Also added in known authentication / authorization errors for commands so that we throw one them vs timing out.
Lastly, moved the terminal length bit to use send_command so that we can pick up errors there as well.
IOS RADIUS Config
```
aaa new-model
aaa authentication password-prompt "AD Password: "
aaa …
```

(FM-7184/FM-7197) Handle authentication errors and custom prompts

---

lib/puppet/util/network_device/cisco_ios/device.rb

Prior to this commit we were not configuring the timeout variable which is 10 seconds by default.
This is inadequate for systems with large configs or higher latency
Default values are now 30 seconds for connection and 120 seconds for commands.
They can be configured in the device config as timeout and command_timeout

(FM-7224) Split command and connection timeout and make configurable

---

spec/acceptance/network_vlan_spec.rb

Explicitly set shutdown as true in applied manifest before expecting this in test

(FM-7283) Fix network_vlan acceptance test

---

lib/puppet/provider/syslog_server/command.yaml
spec/unit/puppet/provider/syslog_server/test_data.yaml

The command `logging host x.x.x.x` has superseded `logging x.x.x.x`.  This PR adds support for both.

(FM-7396) syslog_server match new style hosts

---

lib/puppet/provider/banner/ios.rb

The banner type moved from ios specific to netdev_stdlib.  This PR adds the necessary check for coexistence as implemented in #181

(maint) Add missing coexistence check to banner

---

lib/puppet/provider/network_interface/ios.rb
lib/puppet_x/puppetlabs/cisco_ios/utility.rb
spec/acceptance/network_interface_spec.rb
spec/unit/puppet/provider/network_interface/network_interface_spec.rb
spec/unit/puppet/provider/network_interface/test_data.yaml

This will check for potential non-device compatible fields such as mtu.
If found, remove from proposed changes such that we maintain idempotency.
Note that this requires the network_interface type from netdev_stdlib to
include the 'canonicalize' feature.

(FM-6988) Add canonicalize function to network_interface

---

metadata.json

This module has been tested against Puppet 6 and (future) PE 2019.0 master

(maint) Allow support for Puppet 6

---

README.md

This update provides a note about the required version of the Puppet
agent when using the newer options.

FM-7435 - Wrong Puppet version quoted for 'cisco_ios' module

---

README.md
lib/puppet/util/network_device/cisco_ios/device.rb

This commit will add functionality to create a known_hosts file
with a device fingerprint on first connection.
This will be stored in the cache vardir. The location can be specified
by the user by using the known_hosts_file field in device.conf.
The user can also disable validation by specifying verify_host_key to false.

CVE-2018-11750 (FM-7215) Verify SSH known hosts if specified

---

lib/puppet/provider/banner/ios.rb
lib/puppet/provider/network_dns/ios.rb
lib/puppet/provider/network_interface/ios.rb
lib/puppet/provider/network_snmp/ios.rb
lib/puppet/provider/network_trunk/ios.rb
lib/puppet/provider/network_vlan/ios.rb
lib/puppet/provider/ntp_auth_key/ios.rb
lib/puppet/provider/ntp_config/ios.rb
lib/puppet/provider/ntp_server/ios.rb
lib/puppet/provider/port_channel/ios.rb
lib/puppet/provider/radius_global/ios.rb
lib/puppet/provider/radius_server/ios.rb
lib/puppet/provider/radius_server_group/ios.rb
lib/puppet/provider/snmp_community/ios.rb
lib/puppet/provider/snmp_notification/ios.rb
lib/puppet/provider/snmp_notification_receiver/ios.rb
lib/puppet/provider/snmp_user/ios.rb
lib/puppet/provider/syslog_server/ios.rb
lib/puppet/provider/syslog_settings/ios.rb
lib/puppet/provider/tacacs_global/ios.rb
lib/puppet/provider/tacacs_server/ios.rb
lib/puppet/provider/tacacs_server_group/ios.rb

netdev_stdlib will soon require all providers to implement
simple_get_filter. Since we do not gain anything from that, this commit
only accepts the parameter, but does not do any filtering.

(MODULES-8069) prepare for updates to netdev_stdlib

---

metadata.json
spec/spec_helper_acceptance.rb

Acceptance tests failure as it was ensuring a `puppetserver` while the tests are using a full pe installation rather than just puppetserver.
Changes to spec helper ensures the correct service based on the facts.
Bumping the resource_api dependency boundary.
Should see it works here: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/modules/view/networking/view/ad-hoc/view/cisco_ios/job/forge-module_puppetlabs-cisco_ios_intn-sys_full-pe-current-adhoc/PLATFORM=centos7-64cisco_host%252Cdefault.mdca%257BDEVICE_IP%253D10.0.22.162%252CDEVICE_USER%253Dadmin%252CDEVICE_PASSWORD%253Dbayda.dune.inca.nymph%252CDEVICE_ENABLE_PASSWORD%253Dbayda.dune.inca.nymph%257D,WORKER_LABEL=beaker/53/console 🤞 
Whereas master: 
```
16:05:15 Failure/Error:
16:05:15           apply_manifest(<<PP
16:05:15 …
```

(maint) resolving resource issue when applying manifest

---

lib/puppet/provider/network_interface/cisco_ios.rb
lib/puppet/util/network_device/cisco_ios/device.rb
lib/puppet_x/puppetlabs/cisco_ios/utility.rb

This commit cuts down on the number of prompt retrievals.
It also adds a clear down of the send_command unless specified false.

(maint) Send command and prompt hardening

---

lib/puppet/util/network_device/cisco_ios/device.rb

4.2.0 of net-ssh renamed the `paranoid` option to `verify_host_key` and some Puppet versions are shipped with older versions of net-ssh which meant that `verify_host_key` was not a valid option causing failures.
This commit will use `paranoid` when the version of `net-ssh` is under 4.2.0.

(FM-7604) only use verify_host_key on versions of net-ssh which have it

---

README.md
manifests/init.pp
manifests/install.pp
manifests/install/agent.pp
manifests/install/master.pp
manifests/proxy.pp
manifests/server.pp

With this commit ...
Simply including the module will include the ::install class.
The ::install class will install dependencies on agent or master.
(A custom puppetserver_installed fact, defined by puppetlabs-resource_api,
which is a dependency of this module, is used to detect a master.)
Optionally, the ::install::agent and ::install::master classes can be declared
directly, allowing the user to specify their parameters ... if any.
Keep manifests/*.pp to allow for a transition to these classes.

(FM-7653) implement a standardized install class

---

spec/acceptance/ios_aaa_accounting_spec.rb
spec/acceptance/ios_aaa_authentication_spec.rb
spec/acceptance/ios_aaa_authorization_spec.rb
spec/acceptance/ios_aaa_session_id_spec.rb
spec/acceptance/ios_config_spec.rb
spec/acceptance/network_dns_spec.rb
spec/acceptance/radius_global_spec.rb
spec/acceptance/radius_server_group_spec.rb
spec/acceptance/radius_server_spec.rb
spec/acceptance/tacacs_server_group_spec.rb
spec/acceptance/tacacs_server_spec.rb

Fix acceptance tests such that there are no dependencies on
device config eg. 'aaa new model' or previous domain name

(maint) Fix acceptance tests on fresh device config

---

lib/puppet/util/network_device/cisco_ios/device.rb
spec/acceptance/ios_aaa_accounting_spec.rb
spec/acceptance/ios_aaa_authentication_spec.rb
spec/acceptance/ios_aaa_authorization_spec.rb
spec/acceptance/ios_aaa_session_id_spec.rb
spec/acceptance/radius_global_spec.rb
spec/acceptance/radius_server_group_spec.rb
spec/acceptance/radius_server_spec.rb
spec/acceptance/tacacs_server_group_spec.rb
spec/acceptance/tacacs_server_spec.rb
spec/spec_helper_acceptance.rb

It was found that 'aaa new-model' pre-requisite had the potential
to lock devices out of enable mode. Explicity adding the known
enable secret allows for enable privileged mode to be accessible.

(FM-7737) Add enable secret to test pre-requisite

---

lib/puppet/util/network_device/cisco_ios/device.rb

This change allows us to detect when a device has a passwordless
privilege when entering enable mode, and do not send the password

(maint) Fix for the enable password regex

---

lib/puppet/util/network_device/cisco_ios/device.rb

An OS family fact will allow for differentation between IOS
and IOS XE devices

(maint) Add an OS Family fact

---

spec/unit/puppet/provider/ios_acl_entry/test_data.yaml

Given our conversion function, these values are now properly returned as integers

(maint) Unit tests - ACL entry types should be integers

---

lib/puppet/transport/cisco_ios.rb
lib/puppet/transport/schema/cisco_ios.rb
spec/spec_helper_acceptance.rb

Some devices are configured in away that a user defaults to privalidged mode which means there is no need to set an enable password.

(maint) making enable_password optional

---

lib/puppet/provider/ios_access_list/cisco_ios.rb
lib/puppet/provider/ios_acl_entry/cisco_ios.rb
spec/unit/puppet/provider/ios_access_list/cisco_ios_spec.rb
spec/unit/puppet/provider/ios_acl_entry/cisco_ios_spec.rb

The work done on acls and access lists overlapped with the transport and naming conversion work and the conversion was never done.
This change will bring the acl and access list providers inline with the others and enforce the type requirements.

(maint) acl and access conversion to match other providers

---

README.md
lib/puppet/provider/network_interface/command.yaml

MTU is only supported at a an interface level on 4k and above series devices and is not a limitation of non XE vs XE OS's.
The changes here will exclude the known devices that do not have MTU support at an interface level.

(FM-7748) checking of support for network interface and xe

---

spec/acceptance/network_interface_spec.rb
spec/spec_helper_acceptance.rb

Previously it was only checking line starts with `Error:` or `Warning:` - but colour output in the device runs meant the line started with a colour hex.
This change will highlight areas of the test which are failing across devices.
Also updating the MTU value as some older devices has a lowest bound of 1501.

(maint) updating the error and warning checks

---

README.md
lib/puppet/provider/network_trunk/command.yaml
spec/acceptance/network_trunk_spec.rb

- Encapsulation excluded for all XE devices as only a single encapsulation type is supported
- Port set in test changed to vlan42

(FM-7750) - Network Trunk update to account for XE

---

README.md
spec/acceptance/ntp_config_spec.rb

ntp_config test setup needs to set the interface vlan as well as the network_vlan

FM-7753 XE functionality for ntp_config

---

spec/acceptance/ntp_server_spec.rb
spec/spec_helper_acceptance.rb

Now that we execute locally, we pick up all debug.
One of our test fixtures was picking up all debug output, but we wished to parse only the Puppet device output as yaml.
This commit allows for the verbose, debug, trace option string to be set to an empty string (ie. not set) if desired.

(maint) Fix for NTP Server test

---

spec/acceptance/snmp_notification_spec.rb

As we now return all debug output to the matcher, only try to match when the field is in a Puppet data structure

(maint) SNMP Notification acceptance test fix

---

lib/puppet/provider/tacacs_global/command.yaml
spec/acceptance/tacacs_global_spec.rb

Source interface does not always show, because IOS.
The check needed updated now we output all debug.

(maint) Fix for TACACS Global test

---

spec/acceptance/tacacs_global_spec.rb

The regex in the test’s seems to be getting confused at the square brackets. Adding back ticks looks to fix it.

(maint) Fix for Tacas Global Test

---

lib/puppet/provider/ios_stp_global/command.yaml

The 6503 accepts the portfast bpduguard default command.
However it stores this in config as an 'edge' option.
Amend the regular expression to capture this.

(maint) Fix for IOS STP Global test

---

README.md
lib/puppet/provider/radius_server/command.yaml
spec/acceptance/radius_server_spec.rb

Tests highlight that the Radius Server is not compatible with the test 4948.
Add exclusion to the provider and test spec.

(maint) Add 4948 exclusion to Radius Server

---

lib/puppet/transport/command.yaml

Adds ']' to match on conformation prompts such as aaa new-model

(maint) Update the connection prompt to match on confirmation prompts

---

README.md
lib/puppet/provider/ios_radius_global/cisco_ios.rb
lib/puppet/provider/ios_radius_global/command.yaml
lib/puppet/type/ios_radius_global.rb
lib/puppet_x/puppetlabs/cisco_ios/utility.rb
spec/acceptance/ios_radius_global_spec.rb
spec/unit/puppet/provider/ios_radius_global/cisco_ios_spec.rb
spec/unit/puppet/provider/ios_radius_global/test_data.yaml

This type and provider expands the existing radius_global type and provider to allow for radius server attributes to be set, as per customer request.

(FM-7757) Add IOS_radius_global type and provider

---

lib/puppet/transport/cisco_ios.rb

Example. From:
```
Error: ios_radius_global[default]: Updating: Failed after 1.92 seconds: 'radius-server attribute 25 access-request include
^
% Invalid input detected at '^' marker.
cisco-4507r(config)#' Error sending 'radius-server attribute 25 access-request include'
```
To:
```
Error: ios_radius_global[default]: Updating: Failed after 0.738676 seconds: 
'radius-server attribute 25 access-request include
^
% Invalid input detected at '^' marker.
cisco-4507r(config)#'
Error sending: 'radius-server attribute 25 access-request include'
```

(maint) Improve readability of error messages returned from the device

---

README.md
lib/puppet/provider/ios_network_trunk/cisco_ios.rb
lib/puppet/provider/ios_network_trunk/command.yaml
lib/puppet/provider/network_interface/cisco_ios.rb
lib/puppet/provider/network_trunk/cisco_ios.rb
lib/puppet/provider/network_trunk/command.yaml
lib/puppet/transport/cisco_ios.rb
lib/puppet/type/ios_network_trunk.rb
lib/puppet_x/puppetlabs/cisco_ios/utility.rb
spec/acceptance/ios_network_trunk_spec.rb
spec/unit/puppet/provider/ios_network_trunk/cisco_ios_spec.rb
spec/unit/puppet/provider/ios_network_trunk/test_data.yaml
spec/unit/puppet/provider/network_trunk/cisco_ios_spec.rb
spec/unit/puppet/provider/network_trunk/test_data.yaml
spec/unit/puppet/type/ios_network_trunk_spec.rb

Additional attributes added:
- 'access_vlan', the VLAN which will be used when in access mode.
- 'voice_vlan', configures how IP voice traffic is to be handled.
- 'switchport_nonegotiate', prevents the sending of dynamic trunk port messages when set.
- 'allowed_vlans', designates which VLANs can be used when trunking.

(FM-8181) - Ios Network Trunk created

---

README.md
lib/puppet/provider/ios_additional_syslog_settings/cisco_ios.rb
lib/puppet/provider/ios_additional_syslog_settings/command.yaml
lib/puppet/type/ios_additional_syslog_settings.rb
spec/acceptance/ios_additional_syslog_settings_spec.rb
spec/unit/puppet/provider/ios_additional_syslog_settings/cisco_ios_spec.rb
spec/unit/puppet/provider/ios_additional_syslog_settings/test_data.yaml
spec/unit/puppet/type/ios_additional_syslog_settings.rb

- Attributes are:
- `trap`, the syslog server logging level.
- `origin_id`, an optional id to be added to all syslog messages.

(FM-7764) - IOS Additional Syslog Settings created

---

README.md
lib/puppet/provider/ios_snmp_global/cisco_ios.rb
lib/puppet/provider/ios_snmp_global/command.yaml
lib/puppet/type/ios_snmp_global.rb
spec/acceptance/ios_snmp_global_spec.rb
spec/unit/puppet/provider/ios_snmp_global/cisco_ios_spec.rb
spec/unit/puppet/provider/ios_snmp_global/test_data.yaml
spec/unit/puppet/type/ios_snmp_global_spec.rb

Attributes added:
- trap_source: assigns an interface for the source address of all traps.
- system_shutdown: enables use of the SNMP reload command.
- contact: text for mib object sysContact.
- manager: enables the SNMP manager.
- manager_session_timeout: modifies the SNMP manager timeout parameter.
- ifmib_ifindex_persist: enables IF-MIB ifindex persistence.

(FM-7760) Add ios_snmp_global type and provider

---

README.md

Puppet expects the configuration in HOCON, not Puppet-syntax.

Fix documentation example device conf file

---

README.md
lib/puppet/provider/ios_stp_global/cisco_ios.rb
lib/puppet/provider/ios_stp_global/command.yaml
lib/puppet/type/ios_stp_global.rb
spec/acceptance/ios_stp_global_spec.rb

The `enable` property is something that is only implied so if trying to remove something, i.e. `enable => false` then the value is assigned to a variable and then the property is deleted from the resource in order to maintain idempotency.

(FM-8310) idempotency fixes for ios stp global

---

lib/puppet/provider/ios_snmp_global/cisco_ios.rb
spec/acceptance/ios_snmp_global_spec.rb
spec/unit/puppet/provider/ios_snmp_global/test_data.yaml

Some of the values weren't returning `'unset'` when unmanaged causing idempotency issues. This PR will return the `'unset'` keyword when required.

(maint) fixes for the final ios_snmp_global idempotency failures

---

README.md

The beaker environmental variables are no longer required.

(maint) Remove the no longer needed beaker environment variables

---

TestMatrix.md

As per the RFC 3414 (User-based Security Model (USM) for version 3 of the Simple Network Management Protocol (SNMPv3)) the configuration of these will not be returned from the device which means we cannot support idempotency.

(FM-8323) adding wording around v3 snmp user support

---

README.md
TestMatrix.md
lib/puppet/provider/ios_interface/cisco_ios.rb
lib/puppet/provider/ios_interface/command.yaml
lib/puppet/provider/ios_network_dns/cisco_ios.rb
lib/puppet/type/ios_interface.rb
spec/acceptance/ios_interface_spec.rb
spec/unit/puppet/provider/ios_interface/cisco_ios_spec.rb
spec/unit/puppet/provider/ios_interface/test_data.yaml
spec/unit/puppet/type/ios_interface.rb

- name:  The switch interface name, e.g. "Ethernet1”
- mac_notification_added: Whether to enable Mac Address added notification for this port.
- mac_notification_removed: Whether to enable Mac Address removed notification for this port.
- link_status: Whether to permit duplicate SNMP LINKUP and LINKDOWN traps.
- logging_event: Whether or not to log certain event messages. Any event log not specifically indicated will be disabled.
- logging_event_link_status: Whether to log UPDOWN and CHANGE event messages.
- ip_dhcp_snooping_trust: DHCP Snooping trust config
- ip_dhcp_snooping_limit: DHCP snooping rate limit
- flowcontrol_receive: Flow control (receive) [desired|on|off]

(FM-7760) add ios_interface

---

TestMatrix.md
lib/puppet/provider/ios_access_list/cisco_ios.rb
lib/puppet/provider/ios_acl/cisco_ios.rb
lib/puppet/provider/ios_acl/command.yaml
lib/puppet/provider/ios_acl_entry/cisco_ios.rb
lib/puppet/transport/cisco_ios.rb
lib/puppet/type/ios_access_list.rb
lib/puppet/type/ios_acl.rb
lib/puppet/type/ios_acl_entry.rb
lib/puppet_x/puppetlabs/cisco_ios/utility.rb
spec/acceptance/ios_acl_spec.rb
spec/unit/puppet/provider/ios_acl/cisco_ios_spec.rb
spec/unit/puppet/provider/ios_acl/test_data.yaml
spec/unit/puppet/type/ios_acl_spec.rb

Prior to this work `ios_access_list` allowed for a named access list to be created without function, and  it was not possible to create a numbered access list.
This work merges `ios_access_list` and `ios_acl_entry` into one type: ios_acl_entry.
Resources will use the title_pattern  of `<access_list> <access_list_type> <entry>` e.g. `RepelInvaders extended 10` will create the `RepelInvaders` access list as an `extended` named list with the priority entry `10`.  While `10 standard 10` will create the numbered access list 10 as standard with a priority entry 10.

(FM-7815) Merge functions of ios_access_list and ios_acl_entry

---

spec/spec_helper_acceptance.rb

Previously the DEVICE_IP information would have been passed in through settings on the (unused) centos7 box in the beaker nodeset. After https://github.com/puppetlabs/ci-job-configs/pull/6350 we need to get the info directly from the ABS_RESOURCE_HOSTS, if it is not in the environment.

(maint) clean up acceptance setup to work with new pipelines

---

lib/puppet/transport/cisco_ios.rb

Some older, less secure algorithms have been deprecated with net-ssh 6.x (which is what is available in the context the ace server in PE executes remote tasks). This commit adds an option to net-ssh to include the less secure algorithms which are on the path to deprecation until they are formally deprecated/removed.

(PE-29241) Use all supported algorithms for ssh connections

---

.fixtures.yml
.travis.yml
README.md
manifests/install/agent.pp
manifests/install/server.pp
manifests/proxy.pp
manifests/server.pp
metadata.json

As of puppet6, the resource_api gem is automatically included in Puppet therefore the module has been deprecated. Removing all references to the resource_api module in the codebase.

(IAC-1603) Removing usage of resource_api module and puppet5 support
