metadata.json
Adds some tags to the module for better visibility on forge and SEO.
=> (maint) add tags to metadata

examples/syslog_settings.pp, lib/puppet/provider/syslog_settings/command.yaml, metadata.json, spec/unit/puppet/provider/syslog_settings/test_data.yaml
Adds facility to syslog_settings.  This can be merged once netdev_stdlib is released.
=> (NETDEV-41) add facility to syslog_settings

lib/puppet/provider/banner/command.yaml, lib/puppet/provider/banner/ios.rb, spec/acceptance/banner_spec.rb, spec/unit/puppet/provider/banner/test_data.yaml
This allows for the banner MOTD to be unset.
=> (FM-7028) Add 'unset' function to banner.

lib/puppet/util/network_device/cisco_ios/device.rb
This commit changes when we dump SSH session information.  SSH dump file is only enabled now when --debug is passed to `puppet device` or when debug is set in the device config and `ssh_logging` is set to `true` in the device config.
The default location for the dump file has changed to the ```Puppet[:statedir]``` example ```/opt/puppetlabs/puppet/cache/devices/cat-2960/state/SSH_I_DUMPED```.  Users can specify a file path/name in the device configuration by setting `ssh_log_file` in the config
```
{
"address": "192.168.198.60",
"username": "test",
"password": "test123",
"enable_password": "enableit",
"ssh_logging": true,
"ssh_log_file": "./ssh_log"
}
```
Lastly, world readable has been removed from the SSH dump file
=> CVE-2018-11752 (FM-7259) explicit configuration for SSH session logging

lib/puppet/util/network_device/cisco_ios/device.rb
The Resource API allows a `Hash` with the credentials/config instead
of a `file://` URL [since 1.4.0](https://github.com/puppetlabs/puppet-resource_api/pull/96).
This commit switches over to using the Resource API Device baseclass
to handle this behaviour for us. It also avoids the undeclared dependency
on the hocon gem.
=> (maint) switch the Device to url_or_config handling

.gitlab-ci.yml, .rubocop.yml, .travis.yml, Gemfile, appveyor.yml, metadata.json, spec/default_facts.yml
pdksync_1.7.1-0-g810b982
pdk version: `1.7.1`
=> pdksync - pdksync_1.7.1-0-g810b982

README.md, manifests/init.pp, manifests/install.pp, manifests/install/agent.pp, manifests/install/master.pp, manifests/proxy.pp, manifests/server.pp
Correct and normalize puppet strings data.
=> (FM-7653) implement a standardized install class

lib/puppet/provider/snmp_user/cisco_ios.rb, spec/unit/puppet/provider/snmp_user/test_data.yaml
the "priv" prefix is missing if "des" is selected as "privacy".
This should fix it.
=> make "des" working

lib/puppet/util/task_helper.rb
This reverts commit da6918eecf70952569e47416ca409d0edce24e97.
=> Revert "(maint) remove task_helper "

README.md
The `-` is since they have not been verified, these will be updated as each resource is checked off against them.
Used the following http://markdowntable.com/ for formatting, as it is easier to manage.
=> (maint) adding the new devices to readme test matrix

lib/puppet/transport/cisco_ios.rb, lib/puppet/transport/schema/cisco_ios.rb, spec/spec_helper_acceptance.rb
This reverts commit 592dbc11d324f2c6eaf0b5eeebf82692421f9069.
=> Revert "(maint) making enable_password optional"

lib/puppet/util/network_device/cisco_ios/device.rb, lib/puppet_x/puppetlabs/cisco_ios/transport_shim.rb
This commit will add a function to allow for backwards compatible credentials.
- address  (map to host)
- username (map to user)
=> (maint) Add a function to allow for backwards compatible credentials

.gitignore, .sync.yml, lib/puppet/provider/radius_server_group/cisco_ios.rb, lib/puppet/provider/tacacs_server_group/cisco_ios.rb, spec/acceptance/nodesets/vmpooler.yml, spec/acceptance/ntp_server_spec.rb, spec/acceptance/radius_server_spec.rb, spec/spec_helper_acceptance.rb
- removed PE installation
- adapted tests to run locally
=> (FM-7849) Acceptance test updates

README.md, lib/puppet/provider/port_channel/command.yaml, spec/acceptance/port_channel_spec.rb
- Exclusions added for flow control send
- Test update
=> (FM-7755) - Port Channel update to account for XE

lib/puppet/provider/network_trunk/command.yaml, spec/acceptance/network_trunk_spec.rb
Encapsulation IOS XE exclusion regex fixed.
Encapsulation test match fixed.
=> (maint) Fix for Network Trunk test

spec/acceptance/network_interface_spec.rb
A check was being triggered by mistake. Have updated it to only trigger when it should.
=> (maint) - Network Interface Test Fix

spec/acceptance/tacacs_server_spec.rb
- Have updated the exclusions so that IPV6 incompatible machines are not tested on it.
=> (maint) - Tacacs Server Tests Fix

README.md, lib/puppet/provider/radius_server/command.yaml, spec/acceptance/radius_server_spec.rb, spec/acceptance/tacacs_server_spec.rb
- Exclusions added for tacacs server
- Exclusions added for radius server
=> (maint) - Fix tests of Cisco 4507r

.fixtures.yml, .sync.yml, Gemfile, metadata.json, spec/spec_helper.rb
Update to current PDK templates and cleanups
pdk version: `1.10.0`
=> pdksync - Update to current PDK templates and cleanups

README.md, lib/puppet/provider/ios_network_dns/cisco_ios.rb, lib/puppet/provider/ios_network_dns/command.yaml, lib/puppet/type/ios_network_dns.rb, spec/acceptance/ios_network_dns_spec.rb, spec/unit/puppet/provider/ios_network_dns/cisco_ios_spec.rb, spec/unit/puppet/provider/ios_network_dns/test_data.yaml, spec/unit/puppet/type/ios_network_dns_spec.rb
- ip_domain_lookup attribute added
=> (FM-7747) IOS Network DNS Created

README.md, lib/puppet/provider/syslog_settings/cisco_ios.rb, lib/puppet/provider/syslog_settings/command.yaml, spec/acceptance/syslog_settings_spec.rb, spec/unit/puppet/provider/syslog_settings/cisco_ios_spec.rb, spec/unit/puppet/provider/syslog_settings/test_data.yaml
Not sure about the buffered_* types. Considered moving directly to creating an ios type and just merging them into one.
=> (FM-7764) - Functionality added to Syslog Settings

docs/04-running-a-task/README.md, docs/06-running-a-plan/README.md
A few text changes, most significant change is making sure the user creates a 'plans' directory (with an 's') - otherwise the new plan doesn't show up
=> Minor updates to hands-on lab

.sync.yml, Gemfile, lib/puppet/provider/ios_network_trunk/cisco_ios.rb, lib/puppet/provider/ios_radius_global/cisco_ios.rb, spec/unit/puppet/provider/ios_network_trunk/cisco_ios_spec.rb, spec/unit/puppet/provider/ios_radius_global/cisco_ios_spec.rb
These modules are required for all code, not just unit tests.
=> (maint) environmental acceptance test fixes

README.md, lib/puppet/provider/ios_radius_server_group/cisco_ios.rb, lib/puppet/provider/ios_radius_server_group/command.yaml, lib/puppet/type/ios_radius_server_group.rb, spec/acceptance/ios_radius_server_group_spec.rb, spec/unit/puppet/provider/ios_radius_server_group/cisco_ios_spec.rb, spec/unit/puppet/provider/ios_radius_server_group/test_data.yaml, spec/unit/puppet/type/ios_radius_server_group.rb
- Fix made to radius_server_group
=> (FM-7758) Add type ios_radius_server_group

Rakefile, metadata.json, spec/default_facts.yml
(maint) update pdk-templates
pdk version: `1.13.0`
=> pdksync - (maint) update pdk-templates

lib/puppet/provider/vrf/cisco_ios.rb, lib/puppet/provider/vrf/command.yaml, lib/puppet/transport/cisco_ios.rb, lib/puppet/transport/command.yaml, spec/acceptance/vrf_spec.rb, spec/unit/puppet/provider/vrf/cisco_ios_spec.rb, spec/unit/puppet/provider/vrf/test_data.yaml
(WIP) (FM-8500) Add vrf provider
vrf wip
run_command_vrf_mode created
Add acceptance and unit testing
=> (FM-8500) Add vrf provider

REFERENCE.md, lib/puppet/provider/ios_interface/cisco_ios.rb, lib/puppet/provider/ios_interface/command.yaml, lib/puppet/type/ios_interface.rb, spec/acceptance/ios_interface_spec.rb, spec/spec_helper_acceptance.rb, spec/unit/puppet/provider/ios_interface/test_data.yaml
=> (FM-8501) Add vrf support to ios_interface

TestMatrix.md, lib/puppet/provider/ios_ntp_config/command.yaml, lib/puppet/provider/network_interface/command.yaml, lib/puppet/provider/ntp_server/command.yaml, lib/puppet/provider/radius_server/command.yaml, spec/acceptance/ios_interface_spec.rb, spec/acceptance/ios_ntp_config_spec.rb, spec/acceptance/network_interface_spec.rb, spec/acceptance/ntp_server_spec.rb, spec/acceptance/radius_server_spec.rb, spec/acceptance/snmp_notification_receiver_spec.rb, spec/acceptance/syslog_server_spec.rb, spec/acceptance/tacacs_server_group_spec.rb, spec/acceptance/tacacs_server_spec.rb, spec/acceptance/vrf_spec.rb, spec/spec_helper_acceptance.rb
Includes other exclusions previously missed
=> (FM-8705) - Exclusions added for Cisco-3560

.rubocop.yml, .travis.yml, .vscode/extensions.json, Gemfile, Rakefile, metadata.json, spec/spec_helper.rb
(maint) - Pdk Update
pdk version: `1.17.0`
=> pdksync - (maint) - Pdk Update

metadata.json
This is a pull request for [IAC 1116]
=> (IAC-1116) - updating author to puppetlabs

.sync.yml, Gemfile, README.md, REFERENCE.md, docs/README.md, lib/puppet/transport/schema/cisco_ios.rb, manifests/install.pp, manifests/install/server.pp, manifests/server.pp, spec/acceptance/nodesets/default.yml
Removal of any inappropriate or offensive terminology from the code base.
Includes a backwards incompatible change of a class name
=> (IAC-1020) - removal of Inappropriate Terminology

CHANGELOG.md
=> (maint) v2.0.0 Release Prep

CHANGELOG.md
Reverts puppetlabs/cisco_ios#430
=> Revert "(maint) v2.0.0 Release Prep"
